### ISSUE TITLE
Some characters discarded

### ISSUE THREAD

**Issue by gux2k3** [ZombieWizzard/vita-activator#3]
Hello,
This is a great app but found that if you have the character "%" the app will discard it automatically, im changing my password to try again. Thx

**Comment by ZombieWizzard** [comment]
I'll take a look into it, thanks.

**Comment by ZombieWizzard** [comment]
I have determined that this was only an issue in the display of the username and password and not the actual activation or deactivation. I have however fixed the display in commit 289c1fc28f4e7a43a30e0023ef1f55f1da6e49a9 and may have fixed the issue with your password (if you had another special char like + or @)
