### ISSUE TITLE
"An error has occured, printing debug information..."

### ISSUE THREAD

**Issue by Nozk** [ZombieWizzard/vita-activator#4]
Error: PS Vita Activiation Failed, unknown error....

Installed vpk, and swapped eboot. what else am i missing?

**Comment by ZombieWizzard** [comment]
Does it print correct info for your PSN account below that? If not try choosing to manually input your PSN info, If it's not working already maybe try restarting your router and vita. I'm guessing that it's probably the page failing to load (remember you need to be on wifi for it to work)

**Comment by ZombieWizzard** [comment]
Try using the latest release of Vita Activator https://github.com/ZombieWizzard/vita-activator/releases/latest
