### ISSUE TITLE
Works on the new 2-Step Verification of psn?

### ISSUE THREAD

**Issue by gaudio77** [ZombieWizzard/vita-activator#5]
Good afternoon friend!
I can not activate my PSTV with your app . I get an error message ( failure of login details ) . is it because configured to log in two pasos sony ?

**Comment by gaudio77** [comment]
* two steps. 
I do not know how to install libvita2d too. It works without it ?

**Comment by ZombieWizzard** [comment]
If your using the binary you don't need any additional libraries etc but if your are trying to compile it then you will need vita2d. As for the login detail error message double check the login info is 100% correct

**Comment by ZombieWizzard** [comment]
Also I will look into 2FA if that changes the way the backend works

**Comment by ZombieWizzard** [comment]
Added frontend support for 2FA in v1.1

**Comment by ZombieWizzard** [comment]
Added 2FA frontend support in the latest release bbaf3cc857ea9aa9714a2532c5f70c890fcb5b3d
